package com.techlabs.model;

public class BankTransferPayments implements Payments{

	@Override
	public void processPayment() {
		// TODO Auto-generated method stub
		System.out.println("Payment generated by Bank Transfer");
	}

	@Override
	public void refund() {
		// TODO Auto-generated method stub
		System.out.println("Refund generated by Bank Transfer");
	}

}
