package com.techlabs.model;

public class CreditCardPayments implements Payments{

	@Override
	public void processPayment() {
		// TODO Auto-generated method stub
		System.out.println("Payment generated by Credit Card");
	}

	@Override
	public void refund() {
		// TODO Auto-generated method stub
		System.out.println("Payment generated by Credit Card");
	}

}
