package com.techlabs.model;

public class PayPalPayments implements Payments {

	@Override
	public void processPayment() {
		// TODO Auto-generated method stub
		System.out.println("payment process by paypal");
	}

	@Override
	public void refund() {
		// TODO Auto-generated method stub
		System.out.println("Refund generated by paypal");
	}

}
